name: Import Base images from remote media library

on:
  schedule:
    - cron:  '0 * * * *'
  push:
    branches: [ main, issue-* ]

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  
          submodules: 'true'

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Update submodule
        run: git submodule update --remote

      - name: Pull dataset from remote
        run: cd library && dvc pull --remote azure && cd ..
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

      - name: Copy images from media library (git submodule) to this repo
        run: ./scripts/copy-images.sh

      - name: Show added or modified Base Images
        run:  |
          git status
          git --no-pager diff

      - name: Check if there are new Base images
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            public/images/*.tif
            public/images/*.tiff

      - name: Auto-commit added or modified Base images
        uses: stefanzweifel/git-auto-commit-action@v4
        if: env.GIT_DIFF
        with:
          commit_message: "Add Base images"
          file_pattern: public/images/*.tif public/images/*.tiff

      - name: Build if Base images have been added
        if: env.GIT_DIFF && steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          npm install
          npm run build

      - name: Deploy if Base images have been added
        if: env.GIT_DIFF && steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
