name: Test action auto-commit images

on:
  push:
    branches: [ main, issue-* ]

jobs:
  test_auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto-commit added or modified images
        id: auto-commit
        uses: ./.github/actions/auto-commit-images
        with:
          repository: "${{ github.repository }}"
          repo_dir: "${{ github.workspace }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
